# Generated by Django 4.0.4 on 2022-05-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviescore', '0002_seed_movies'),
    ]

    operations = [
        migrations.RunSQL(
            """
                INSERT INTO auth_user (password,is_superuser,username,email,last_name,is_staff,is_active,date_joined,first_name) VALUES ('pbkdf2_sha256$320000$o7SPowhw5NpaHaR4fmBftX$BsO5ROTpBjpLfNUVaXRHhVE4kWs7XOtPr8ta77+Yo1k=',0,'maria','maria@gmail.com','',0,1,'2022-05-14 13:51:13.119414','');
                INSERT INTO auth_user (password,is_superuser,username,email,last_name,is_staff,is_active,date_joined,first_name) VALUES ('pbkdf2_sha256$320000$o7SPowhw5NpaHaR4fmBftX$BsO5ROTpBjpLfNUVaXRHhVE4kWs7XOtPr8ta77+Yo1k=',0,'joao','joao@gmail.com','',0,1,'2022-05-14 13:51:13.119414','');
                INSERT INTO auth_user (password,is_superuser,username,email,last_name,is_staff,is_active,date_joined,first_name) VALUES ('pbkdf2_sha256$320000$o7SPowhw5NpaHaR4fmBftX$BsO5ROTpBjpLfNUVaXRHhVE4kWs7XOtPr8ta77+Yo1k=',0,'ana','ana@gmail.com','',0,1,'2022-05-14 13:51:13.119414','');
                INSERT INTO auth_user (password,is_superuser,username,email,last_name,is_staff,is_active,date_joined,first_name) VALUES ('pbkdf2_sha256$320000$o7SPowhw5NpaHaR4fmBftX$BsO5ROTpBjpLfNUVaXRHhVE4kWs7XOtPr8ta77+Yo1k=',0,'lucia','lucia@gmail.com','',0,1,'2022-05-14 13:51:13.119414','');
                INSERT INTO auth_user (password,is_superuser,username,email,last_name,is_staff,is_active,date_joined,first_name) VALUES ('pbkdf2_sha256$320000$o7SPowhw5NpaHaR4fmBftX$BsO5ROTpBjpLfNUVaXRHhVE4kWs7XOtPr8ta77+Yo1k=',0,'joaquim','joaquim@gmail.com','',0,1,'2022-05-14 13:51:13.119414','');
            """,
            reverse_sql=migrations.RunSQL.noop),
    ]
