# Generated by Django 4.0.4 on 2022-05-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviescore', '0004_seed_scores'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='movie',
            order_with_respect_to='title',
        ),
    ]
